CREATE TABLE tbcategory(cateId INT AUTO_INCREMENT, CATETITLE VARCHAR(255))

insert into tbcategory (CATETITLE ) values ( 'Dramatic')
insert into tbcategory (CATETITLE ) values ( 'Love')
insert into tbcategory (CATETITLE ) values ( 'Romantic')
insert into tbcategory (CATETITLE ) values ( 'Dream')
insert into tbcategory (CATETITLE ) values ( 'LifeStyle')
insert into tbcategory (CATETITLE ) values ( 'Modern')
insert into tbcategory (CATETITLE ) values ( 'Old')
insert into tbcategory (CATETITLE ) values ( 'New')
insert into tbcategory (CATETITLE ) values ( 'Society')

create table tbArticle (id bigint auto_increment,title varchar,author varchar,CATEID int ,des varchar,img varchar,foreign key (CATEID) references tbcategory (cateId) on delete cascade on update cascade)

insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',2,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',1,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',8,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')

insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',2,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',1,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',8,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')

insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',2,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',1,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',8,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')

insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',2,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',1,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',8,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')

insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',2,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',1,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',8,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')

insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',2,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',1,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',7,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',8,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',6,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',3,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',5,'very good','user.png')
insert into tbArticle (title,author ,CATEID ,des,img) values('New world','Khmer',4,'very good','user.png')
